/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#151c22",
        "on-secondary-fixed": "#001c39",
        "on-secondary-container": "#003e73",
        "surface-tint": "#934b00",
        "error-container": "#ffdad6",
        "surface-dim": "#d4dbdd",
        "inverse-primary": "#ffb781",
        "on-error-container": "#93000a",
        "inverse-surface": "#2b3234",
        "surface-container": "#e8eff1",
        "on-tertiary-fixed-variant": "#40484e",
        "on-error": "#ffffff",
        "surface-variant": "#dde4e6",
        "primary": "#934b00",
        "surface-bright": "#f4fafd",
        "on-primary-container": "#5f2e00",
        "on-surface-variant": "#554337",
        "surface-container-highest": "#dde4e6",
        "inverse-on-surface": "#ebf2f4",
        "tertiary-container": "#9fa6ae",
        "outline": "#887365",
        "on-tertiary-container": "#353c42",
        "surface-container-lowest": "#ffffff",
        "secondary": "#0060ac",
        "background": "#f4fafd",
        "secondary-container": "#68abff",
        "on-background": "#161d1f",
        "on-primary": "#ffffff",
        "surface-container-high": "#e2e9ec",
        "on-primary-fixed-variant": "#703800",
        "primary-fixed": "#ffdcc4",
        "tertiary-fixed": "#dce3eb",
        "primary-container": "#f28c33",
        "surface": "#f4fafd",
        "secondary-fixed": "#d4e3ff",
        "outline-variant": "#dbc2b1",
        "on-secondary-fixed-variant": "#004883",
        "on-primary-fixed": "#301400",
        "error": "#ba1a1a",
        "on-surface": "#161d1f",
        "tertiary": "#585f66",
        "secondary-fixed-dim": "#a4c9ff",
        "surface-container-low": "#eef5f7",
        "tertiary-fixed-dim": "#c0c7cf",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#ffb781",
        "on-tertiary": "#ffffff"
      },
      spacing: {
        "lg": "48px",
        "xl": "80px",
        "xs": "4px",
        "md": "24px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "base": "8px",
        "max-width": "1200px",
        "margin-desktop": "auto",
        "sm": "12px"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        sans: ['Nunito', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
      }
    },
  },
  plugins: [],
}

